# Generated by Django 3.1.7 on 2021-05-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotify', '0004_auto_20210523_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='album',
            name='no_songs',
        ),
        migrations.AddField(
            model_name='album',
            name='relase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
