# Generated by Django 3.1.7 on 2021-05-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotify', '0005_auto_20210524_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='relase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
