# Generated by Django 3.1.7 on 2021-05-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zotify', '0006_auto_20210524_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='mp3',
        ),
        migrations.RemoveField(
            model_name='song',
            name='number_of_plays',
        ),
        migrations.RemoveField(
            model_name='song',
            name='rating',
        ),
    ]
