# Generated by Django 3.1.7 on 2021-05-24 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zotify', '0007_auto_20210524_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('pseudonym', models.CharField(max_length=50)),
                ('artist', models.ManyToManyField(to='zotify.Artist')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zotify.role')),
            ],
        ),
    ]
