# Generated by Django 3.1.7 on 2021-05-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotify', '0008_member_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='monthly_listeners',
        ),
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
