# Generated by Django 3.1.7 on 2021-05-24 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zotify', '0009_auto_20210524_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='artist',
        ),
        migrations.CreateModel(
            name='MemberArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zotify.artist')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zotify.member')),
            ],
        ),
    ]
