# Generated by Django 3.1.7 on 2021-05-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotify', '0013_auto_20210527_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
