# Generated by Django 3.1.7 on 2021-05-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotify', '0014_auto_20210528_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='268.jpg', null=True, upload_to=''),
        ),
    ]
