# Generated by Django 3.1.7 on 2021-05-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotify', '0015_auto_20210528_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='desc',
            field=models.CharField(blank=True, default='Default description', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='image0.gif', null=True, upload_to=''),
        ),
    ]
