# Generated by Django 3.1.7 on 2021-05-28 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zotify', '0016_auto_20210528_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zotify.genre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ForeignKey(default='brak', null=True, on_delete=django.db.models.deletion.PROTECT, to='zotify.role'),
        ),
    ]
