# Generated by Django 3.1.7 on 2021-05-28 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zotify', '0017_auto_20210528_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ForeignKey(default='brak', null=True, on_delete=django.db.models.deletion.CASCADE, to='zotify.role'),
        ),
    ]
