from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('', views.main, name='zotify-home'),
    path('albums/', views.albums, name='albums'),
    path('artists/', views.artists, name='artists'),
    path('genres/', views.genres, name='genres'),
    path('playlists/', views.playlists, name='playlists'),
    path('playlists/<int:user_id>/', views.playlists, name='playlists'),
    path('album_details/<int:album_id>/', views.album_details, name='album_details'),
    path('artist_details/<int:artist_id>/', views.artist_details, name='artist_details'),
    path('playlist_details/<int:playlist_id>/', views.playlist_details, name='playlist_details'),
    path('song_form/', views.song_form, name='song_form'),
    path('delete_album/<int:album_id>/', views.delete_album, name='delete_album'),
    path('album_form/', views.album_form, name='album_form'),
    path('genre_form/', views.genre_form, name='genre_form'),
    path('profile_page/<int:user_id>/', views.profile_page, name='profile_page'),
    path('songs/', views.songs, name='songs'),
    path('edit_album/<int:album_id>/', views.edit_album, name='edit_album'),
    path('edit_song/<int:song_id>/', views.edit_song, name='edit_song'),
    path('edit_member/<int:member_id>/', views.edit_member, name='edit_member'),
    path('members/', views.members, name='members'),
    path('roles/', views.roles, name='roles'),
    path('add_playlist/', views.add_playlist, name='add_playlist'),
    path('add_member/', views.add_member, name='add_member'),
    path('add_role/', views.add_role, name='add_role'),
    path('add_band/', views.add_band, name='add_band'),
    path('profile_list/', views.profile_list, name='profile_list'),
    path('add_song_to_playlist/<int:song_id>/', views.add_song_to_playlist, name='add_song_to_playlist'),
    path('edit_artist/<int:artist_id>/', views.edit_artist, name='edit_artist'),
    path('delete_artist/<int:artist_id>/', views.delete_artist, name='delete_artist'),
    path('simple_edit/<int:item_id>/', views.edit_genre, name='edit_genre'),
    path('delete_member/<int:member_id>/', views.delete_member, name='delete_member'),
    path('delete_playlist/<int:playlist_id>/', views.delete_playlist, name='delete_playlist'),
    path('delete_song/<int:song_id>/', views.delete_song, name='delete_song'),
    path('add_member_to_band/<int:member_id>/', views.add_member_to_band, name='add_member_to_band'),
    path('delete_profile/<int:user_id>/', views.delete_profile, name='delete_profile'),
    path('edit_playlist/<int:playlist_id>/', views.edit_playlist, name='edit_playlist'),
    path('edit_profile/<int:user_id>/', views.edit_profile, name='edit_profile'),
    path('delete_genre/<int:genre_id>/', views.delete_genre, name='delete_genre'),
    path('delete_song_from_playlist/<int:song_playlist_id>/', views.delete_song_from_playlist,
         name='delete_song_from_playlist'),
    path('delete_member_from_band/<int:band_member_id>/', views.delete_member_from_band,
         name='delete_member_from_band'),
    path('widok', views.widok)
]
